<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Rubencho.Domain</AssemblyName>
    <RootNamespace>Rubencho.Domain</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

</Project>
